### ISSUE TITLE
Still outdated according to Gnome

### ISSUE THREAD

**Issue by j0hannes** [zzrough/gs-extensions-drop-down-terminal#101]
just a hint

**Comment by zzrough** [comment]
you're on 3.16 and it shows as outdated?

**Comment by j0hannes** [comment]
I actually got it to run via gnome-tweak-tool, but now there's a display bug (the first 1.5 lines are hidden behind the top bar and there's 1.5 lines of space at the bottom, even at 100%).

**Comment by l300lvl** [comment]
i would wonder, is this a dup of #98 

i do NOT see this problem on 3.16 and the latest version of ddt, is there a way to duplicate your results @j0hannes ?

**Comment by j0hannes** [comment]
I saw that issue, but only read the first text, which describes the opposite behaviour. I can confirm that it occurs when there is another screen in the virtual prolongation of that one where the terminal is shown on. If I move the other screen to one side so that only the corners of both are touching, the terminal position looks fine.

These screenshot depict what the (reproducible) behaviour:
![screenshot from 2015-04-11 23-30-12](https://cloud.githubusercontent.com/assets/3944397/7103345/cdd8df92-e0a2-11e4-97dc-f2ccc1605e8d.png)
![screenshot from 2015-04-11 23-29-41](https://cloud.githubusercontent.com/assets/3944397/7103346/cdf98314-e0a2-11e4-9460-838a899dc0bb.png)

**Comment by sharan01** [comment]
outdated on gnome 3.16 please update

**Comment by l300lvl** [comment]
@sharan01 which distro are you using??

**Comment by sharan01** [comment]
@l300lvl archlinux

**Comment by sharan01** [comment]
![screenshot from 2015-04-15 00-13-54](https://cloud.githubusercontent.com/assets/1240154/7144745/24e3a7a4-e305-11e4-890e-739c77cb840f.png)

**Comment by l300lvl** [comment]
@sharan01 that happens when youve updated your gnome-shell version and then there is the green arrow which is to update the extension, this lets you update it and will only be available if there is a newer version of the extension available for the shell version you have updated to.

**Comment by zzrough** [comment]
No issue then (Positionning seems to be #98 indeed)
