### ISSUE TITLE
Copy / Paste menu broken with GNOME 3.16

### ISSUE THREAD

**Issue by johnpatcher** [zzrough/gs-extensions-drop-down-terminal#103]
With the recent upgrade to GNOME 3.16 (running on Arch Linux) the copy/paste menu looks broken for me:

![Example of broken menu](https://i.imgur.com/JSUu7aB.png)

Let me know if you need additional information in order to tackle this bug.

**Comment by zzrough** [comment]
Already reported and with a proposed patch in #100
