### ISSUE TITLE
custom command to use drop down with terminal multiplexer

### ISSUE THREAD

**Issue by k0377** [zzrough/gs-extensions-drop-down-terminal#107]
I would like to use tmux in my dropdown terminal, but wonder what is the custom command to do so? I tried `gnome-terminal -e tmux` but this will spawn infinite terminals! :loop:

example: https://youtu.be/XBA3Z5TE_Qw

**Comment by frol** [comment]
Hmm, I'm using tmux too, but haven't any problems with just `/usr/bin/tmux`... Doesn't it work for you?

**Comment by k0377** [comment]
Thanks, this is the right command!
