### ISSUE TITLE
map fn or capslock key as custom command

### ISSUE THREAD

**Issue by k0377** [zzrough/gs-extensions-drop-down-terminal#110]
I would like to use the `fn` key on my notebook to trigger the drop down terminal. The default command is a bad choice if you want to use github flavoured markdown. 

Also it is not possible to map capslock.

**Comment by imnotjames** [comment]
The `fn` key on your notebook probably doesn't come through as an actual key - it might not even come through as a meta key.

`capslock` comes through as a special key as well and Gnome will refuse to bind it as an accelerator.  Even if you did, you'd open your terminal AND THEN TYPE EVERYTHING IN UPPERCASE OH NO. :laughing: 

Your best bet to my knowledge is to remap your keys with hwdb rules.. but it still probably won't help with your `fn` key.
