### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by TonicArtos** [zzrough/gs-extensions-drop-down-terminal#112]
Just checking to see if this project has been dropped by the original developer. Thanks.

**Comment by jcuenod** [comment]
Yes, 4th of June last issue was closed

**Comment by TonicArtos** [comment]
Are you saying it is still maintained? I asked because I sent an email to the developer a couple of weeks ago and I haven't received a reply. Also, there hasn't been any activity with pending pull requests, and the issues are slowly piling up. I don't have an especially strong interest in picking up the project, but if the state continues for too long, I may managing my own fork and start publishing updates to the gnome extensions site.

**Comment by zzrough** [comment]
TonicArtos: Sorry, I'm back from holidays and I saw your PR, thanks a lot for it, but I'm busy with real life at the moment. I just do not check my emails regularly during holidays. I'll merge it as soon as I can.

**Comment by TonicArtos** [comment]
@zzrough Hi, that is great news. Feel free to get in touch if there is anything you need help with.
