### ISSUE TITLE
Feature request: close terminal with exit

### ISSUE THREAD

**Issue by zapashcanon** [zzrough/gs-extensions-drop-down-terminal#145]
Hi,

Would be great if we could close the terminal by entering exit.

I'm not sure, but a few times ago, it worked, no ?

**Comment by xbonio** [comment]
+1 from me. Exit would be great for instant leave the terminal. Lots of popups and modals are implemented this way.

**Comment by BjoernDaase** [comment]
I would also love to see this because then it would behave like all other terminal emulators.

**Comment by pwnorbitals** [comment]
Has this been closed because this has been implemented @zapashcanon ?

**Comment by redianthus** [comment]
No, because I want to clean issues I opened and I don't use this extension or gnome anymore... This project seems unmaintained so it's unlikely it'll be fixed one day.

**Comment by pwnorbitals** [comment]
Well, we never know, there could well be a maintainer who would bring this back to life ! I think it’s worth keeping it open tbh

**Comment by redianthus** [comment]
Feel free to open a new one if you want. :)
