### ISSUE TITLE
Feature request/bugfix: Make text not become transparant

### ISSUE THREAD

**Issue by smurfendrek123** [zzrough/gs-extensions-drop-down-terminal#147]
When i make the terminal partially transparent the text also becomes transparent, In my opinion, only the background should become transparent, like in the default gnome terminal.

See the attached screenshot for a comparison of 50% transparency in the dropdown terminal vs the default gnome terminal. Love the extension by the way.

![screenshot from 2016-04-28 01-41-09](https://cloud.githubusercontent.com/assets/18269095/14871455/8ffe8ba0-0ce2-11e6-8315-ad4fb6c75850.png)

There seems to be a pull request that fixes this https://github.com/zzrough/gs-extensions-drop-down-terminal/pull/144

**Comment by letorbi** [comment]
This issue has been fixed with #152, so it can be closed by either you or @zzrough.
