### ISSUE TITLE
Wrong resize with panel mode Dash to Dock

### ISSUE THREAD

**Issue by thepasto** [zzrough/gs-extensions-drop-down-terminal#149]
I'm using Drop Down Terminal with Dash to Dock extension, panel option enabled. When i open the dropdown extension, the window is not correctly resized, but it goes under the dock.
In the past it were resized as well. [Here's an image ](https://drive.google.com/file/d/0B-yQDH0HYifnM0dsV1cxS3JQM0k/view?usp=sharing).
I already post a bug report to [Dash To Dock](https://github.com/micheleg/dash-to-dock/issues/301) issue tracker too

Thanks

**Comment by thepasto** [comment]
After some investingation, i found the problem, i changed the WindowTypeHint to DROPDOWN_MENU in terminal.js. It seems to work as well, no problem so far, but i will do some test in these days

Thanks

**Comment by KAMiKAZOW** [comment]
The bug should be fixed after https://github.com/zzrough/gs-extensions-drop-down-terminal/pull/140 but for whatever reason there is no new release.

**Comment by zzrough** [comment]
I republished just now, it's pending review so it should be available tomorrow. I just did not find time to do this before.
