### ISSUE TITLE
Transparency not working?

### ISSUE THREAD

**Issue by ddulic** [zzrough/gs-extensions-drop-down-terminal#153]
Any reason why transparency is not working? Setting the value lower just changes the color to the theme color, text also disappears and blends into the color, the below image has "80" set under transparency.

![screenshot from 2016-07-14 17-03-26](https://cloud.githubusercontent.com/assets/10076428/16844308/f084858a-49e4-11e6-88b4-fa29a3ce4a93.png)

**Comment by MedicMomcilo** [comment]
I am facing the same issue, however I believe that extension just isn't synchronized between github and extensions.gnome.org.

Most likely it would work fine if you used latest github version.

**Comment by zzrough** [comment]
yep, sorry I did not have time to republish, I'll do that soon

**Comment by ddulic** [comment]
Thanks for the clarification. I was wondering why it didn't work :O

**Comment by zzrough** [comment]
I republished just now, it's pending review so it should be available tomorrow.
