### ISSUE TITLE
BUG: Latest update inteferes with gnome lock screen

### ISSUE THREAD

**Issue by NITEMAN** [zzrough/gs-extensions-drop-down-terminal#158]
After updating exensions page shows "ERROR banner for this extension and lock screen becomes unusable (can't unlock the screen)

Shell version: 3.14.4 (Debian Jessie)

**Comment by sdt-ork** [comment]
Do you have any message in shell logs, systemctl, xsession-errors or something about the extension? Please try to remove and reinstall the extension, and/or restart gnome-shell (Alt+F2, type the letter r, then the enter key) ... sometimes the update mechanism fails.

**Comment by NITEMAN** [comment]
I've tried to reinstall the extension (via extensions page), gnome reload, etc. without success.

I can't gather logs right now (already lost a couple of work hours on this), but I'll try next week. Right now I've removed the extension.

**Comment by HayafE** [comment]
Same issue here with Gnome 3.14.4 on Red-Hat.
I tried several times to reinstall the extension, restart the gnome-shell, and even reboot several times.  The only solution that worked was to remove the extension.

**Comment by zzrough** [comment]
Do you have any kind of log? (see my earlier comment) Otherwise I'll have to prepare a VM to fix this.

**Comment by HayafE** [comment]
Does this help:

Aug 24 09:39:55 jordanf-tp gnome-session[2973]: Gjs-Message: JS LOG: Extension "drop-down-terminal@gs-extensions.zzrough.org" had error: TypeError: Main.legacyTray is undefined
Aug 24 09:39:56 jordanf-tp gnome-session[2973]: (gnome-shell:3301): Gjs-WARNING **: JS ERROR: GLib.Error dbus-glib-error-quark: The name org.freedesktop.Telepathy.AccountManager was not provided by any .service files
Aug 24 09:40:55 jordanf-tp gnome-session[2973]: Gjs-Message: JS LOG: Extension "drop-down-terminal@gs-extensions.zzrough.org" had error: TypeError: Main.legacyTray is undefined
Aug 24 09:40:55 jordanf-tp gnome-session[2973]: Gjs-Message: JS LOG: Extension "drop-down-terminal@gs-extensions.zzrough.org" had error: TypeError: Main.legacyTray is undefined
Aug 24 09:40:55 jordanf-tp gnome-session[2973]: Gjs-Message: JS LOG: Extension "drop-down-terminal@gs-extensions.zzrough.org" had error: TypeError: Main.legacyTray is undefined
Aug 24 09:40:55 jordanf-tp gnome-session[2973]: Gjs-Message: JS LOG: Extension "drop-down-terminal@gs-extensions.zzrough.org" had error: TypeError: Main.legacyTray is undefined
Aug 24 09:40:55 jordanf-tp gnome-session[2973]: Gjs-Message: JS LOG: Extension "drop-down-terminal@gs-extensions.zzrough.org" had error: TypeError: Main.legacyTray is undefined
Aug 24 09:40:55 jordanf-tp gnome-session[2973]: Gjs-Message: JS LOG: Extension "connectionmanager2@ciancio.net" had error: TypeError: this.viewSelector.removeSearchProvider is not a function
Aug 24 09:40:55 jordanf-tp gnome-session[2973]: Gjs-Message: JS LOG: Extension "drop-down-terminal@gs-extensions.zzrough.org" had error: TypeError: Main.legacyTray is undefined
Aug 24 09:40:55 jordanf-tp gnome-session[2973]: Gjs-Message: JS LOG: Extension "drop-down-terminal@gs-extensions.zzrough.org" had error: TypeError: Main.legacyTray is undefined
Aug 24 09:40:55 jordanf-tp gnome-session[2973]: Gjs-Message: JS LOG: Extension "drop-down-terminal@gs-extensions.zzrough.org" had error: TypeError: Main.legacyTray is undefined
Aug 24 09:40:55 jordanf-tp gnome-session[2973]: Gjs-Message: JS LOG: Extension "drop-down-terminal@gs-extensions.zzrough.org" had error: TypeError: Main.legacyTray is undefined
Aug 24 09:40:55 jordanf-tp gnome-session[2973]: Gjs-Message: JS LOG: Extension "drop-down-terminal@gs-extensions.zzrough.org" had error: TypeError: Main.legacyTray is undefined

**Comment by zzrough** [comment]
a *lot*! Thanks!

(this is a regression of a fix -- but the legacy panel has been
introduced in 3.16 only)
