### ISSUE TITLE
Notification bar pushes Terminal up

### ISSUE THREAD

**Issue by katastrophal** [zzrough/gs-extensions-drop-down-terminal#16]
The terminal is supposed to be some kind of Overlay and integrated with the top bar, but it gets pushed up and under the top bar when the Notification Bar on the bottom is triggered.

**Comment by katastrophal** [comment]
This bug report should be obsolete as of Gnome 3.16, as there is no notification bar any more.

**Comment by zzrough** [comment]
Very true, thanks.
