### ISSUE TITLE
Gnome 3.22 fix for beginners

### ISSUE THREAD

**Issue by fjsaezm** [zzrough/gs-extensions-drop-down-terminal#166]
I've been using this extension for a long time and since I upgraded Gnome to 3.22 version I haven't been able to install it from [Gnome extensions](https://extensions.gnome.org/extension/442/drop-down-terminal/).

I've read that there's a solution for the problem. However, I couldn't find the way to install the extension.

Can someone explain me how you did it?
Thanks!

**Comment by SvetlinZarev** [comment]
1. Download https://github.com/zzrough/gs-extensions-drop-down-terminal/archive/master.zip
2. Extract the folder named 'drop-down-terminal@gs-extensions.zzrough.org' into ~/.local/share/gnome-shell/extensions
3. Enjoy the extension

**Comment by fjsaezm** [comment]
@SvetlinZarev everything working out well now! Thank you so much!

**Comment by Tychus** [comment]
doesn't work
