### ISSUE TITLE
Doesn't install Fed 25 Gnome 3.22.1

### ISSUE THREAD

**Issue by Tychus** [zzrough/gs-extensions-drop-down-terminal#167]
couldn't install the terminal on a new fedora 25 install

**Comment by xmetaxfedyx** [comment]
Same issue here. 

1. Toggled ON on extension page
2. Clicked 'Install'
3. Doesn't appear in installed extensions list on website or Gnome Tweak tool 
4. Running Fedora 25 Gnome 3.22

Worked fine on Fedora 24.

**Comment by igemnace** [comment]
Have you tried the steps in [this issue?](https://github.com/zzrough/gs-extensions-drop-down-terminal/issues/164)

Extensions page seems to have an older version of this extension.

**Comment by emmanueltouzery** [comment]
yes for me I needed to follow these steps:
https://github.com/zzrough/gs-extensions-drop-down-terminal/issues/166#issuecomment-257159761

and that, on two computers. Something is definitely wrong with the version on the gnome extensions page.

**Comment by parasense** [comment]
Experiencing same problem stated in comments above, by xmetaxfedyx:
* Fedora 25, Wayland, Gnome 3.22.2
* Firstly Drop Down Terminal was not findable (using search) on extensions.gnome.org, had to Google search to find the permalink: (https://extensions.gnome.org/extension/442/drop-down-terminal/)
* Toggle the slider, and agree to install.
* Nothing happens.
* The extension is NOT present at ~/.local/share/gnome-shell/extensions/
* Followed the link here to github, downloaded the zip archive, extracted to ~/.local/share/gnome-shell/extensions/drop-down-terminal@gs-extensions.zzrough.org/
* Still not appearing in my extensions via https://extensions.gnome.org/local/ or Tweak tool.
* I have even manually added 3.22.2 in the extension just in case that was the issue, and made no difference.

Any suggestions?

**Comment by zapashcanon** [comment]
@parasense, just add `3.22` not `3.22.2` and restart gnome-shell. (Or restart computer). Then it should be available in tweak tool.

**Comment by zzrough** [comment]
Mmmh I totally failed to release for 3.22 for the first time. I've uploaded support for 3.22 from the PR https://github.com/zzrough/gs-extensions-drop-down-terminal/pull/173 a couple of minutes ago. Should be available in the next 24h.
