### ISSUE TITLE
[Feature request] Please add tabs support

### ISSUE THREAD

**Issue by maciej-c** [zzrough/gs-extensions-drop-down-terminal#170]
Hello dev(s). For me any terminal emulator without ability to run multiple instances in tabs is completely useless. Now when I switched to Fedora 25 and Wayland, I can't effectively run Guake anymore, so this extension appears to be only option for drop-down terminal, but without tabs is unusable...

**Comment by davidcl** [comment]
I was also affected by this issue but switched to `tmux` for managing tab internally rather. It maximize the terminal size and allow a complex tab placement.

**Comment by maciej-c** [comment]
@davidcl Yes you're right, I discovered `tmux` after writing this issue and it's definitely a better solution.

**Comment by razvanc-r** [comment]
@maciej-c you should close this issue then :P
