### ISSUE TITLE
Doesn't work on Fedora 25

### ISSUE THREAD

**Issue by julioEY7** [zzrough/gs-extensions-drop-down-terminal#177]
I just update mi system to Fedora 25 and now every time I try to drop down the terminal,  just give me that message, this terminal just make my life better, please help!

![captura de pantalla de 2017-02-04 11-20-04](https://cloud.githubusercontent.com/assets/22033474/22620196/e77ab80a-eacb-11e6-9cd9-51c928a9d8ad.png)

**Comment by jmayday** [comment]
This issue has been already reported some time ago and it was fixed. I think you just have to reinstall.

**Comment by julioEY7** [comment]
It works! Thaks :D
