### ISSUE TITLE
[FEATURE REQUEST] Ability to escape toggle key (for typing backticks)

### ISSUE THREAD

**Issue by tuxxi** [zzrough/gs-extensions-drop-down-terminal#208]
Hello,

I love your extension, especially the default key "~"; I'm very used to pressing that key from Quake and Counter-Strike and COD4. 

However, when writing in applications such as Discord and Slack with markdown support, where backticks " ` " are used for typing code snippets, I find myself getting frustrated that there is no way to escape the toggle key to type a backtick. Please add a feature to escape the toggle key, perhaps with control+shift+$toggle or control+alt+$toggle, so users can type the toggle key when needed.

Thank you!

**Comment by erkinalp** [comment]
It is easy. I have changed hotkey to Alt+Pause.

**Comment by zzrough** [comment]
@tuxxi you can change the shortcut in the preferences dialog in the Activation > Customshortcut setting. Click in the field and you can set hatever you want such as ctrl-alt+back tick or whatever suites you more, as it depends on the layout keyboard.
