### ISSUE TITLE
Add support for Gnome 3.30

### ISSUE THREAD

**Issue by davidsmd** [zzrough/gs-extensions-drop-down-terminal#217]
Apparently 3.30 breaks some extensions. Pixel-saver's fix for it, pulled from dash to dock, looks like it's pretty short and seems to be working correctly on Ubuntu 18.10 with Gnome 3.30

https://github.com/deadalnix/pixel-saver/pull/174/commits/ea29c6db84412ace8d5f25a99abdfff5770efe6b

If I'm feeling ambitious in the next couple of days, I'll try to submit a PR.

**Comment by anarchodin** [comment]
I sent #219, which solved the issue on my machine. Haven't tested on old GNOMEs, though.

**Comment by davidsmd** [comment]
Nice! Tried it out locally here on 3.30, looks good to me. Will save me an awful lot of cursing. Thanks!

**Comment by zzrough** [comment]
I'm in holidays, we'll do as soon as i can.

Le 21 septembre 2018 11:25:08 GMT+00:00, Daniel Debny <notifications@github.com> a écrit :
>@zzrough Can You update this repo?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/zzrough/gs-extensions-drop-down-terminal/issues/217#issuecomment-423500129

--S

**Comment by zzrough** [comment]
PR merged.
