### ISSUE TITLE
It Interferes with the Native GNOME fonts.

### ISSUE THREAD

**Issue by BhargavSatya** [zzrough/gs-extensions-drop-down-terminal#224]
I have enabled different fonts for my ubuntu.
and the drop-down  inherits the native fonts , but doesn't render them very well, whereas my normal Terminal Window renders it well. 
![screenshot from 2018-11-03 20-48-46](https://user-images.githubusercontent.com/24696554/47953928-df159200-dfa9-11e8-89ec-1e915e1c6b85.png)

**Comment by ph15041996** [comment]
Go to Edit->Preferences Click on the custom and see the font name and then open tweak-tool->fonts in monospace set the same font name. You will same same font as the terminal . I hope it helps :-)
