### ISSUE TITLE
Crashes in gnome-shell 3.36

### ISSUE THREAD

**Issue by MarcObvious** [zzrough/gs-extensions-drop-down-terminal#237]
JS ERROR: TypeError: actor.get_allocation_geometry is not a function

**Comment by MarcObvious** [comment]
vfunc_paint: function(paintContext) {
        let actor = this.get_actor();
        let alloc = actor.get_allocation_box();
        
        actor.continue_paint(paintContext);

        Cogl.set_source_color(this._color);
        Cogl.path_round_rectangle(0, alloc.get_height(), alloc.get_width(), alloc.get_height() - this._width);
    },

**Comment by frol** [comment]
@MarcObvious You saved my day! I confirm that the patches from @MarcObvious `patch-1` branch work for me on Arch Linux with Gnome Shell 3.36.

**Comment by mokilcde** [comment]
That patch also works for me! Thanks for that

**Comment by ericdallo** [comment]
@zzrough, can we merge this?

**Comment by zzrough** [comment]
@ericdallo hello, will try to do this tonight

**Comment by zzrough** [comment]
done, thanks! Update pushed on extensions.gnome.org

**Comment by ericdallo** [comment]
Thanks @zzrough, maybe we should add compatibility to 3.36 [here](https://github.com/zzrough/gs-extensions-drop-down-terminal/blob/master/drop-down-terminal%40gs-extensions.zzrough.org/metadata.json#L6)?

**Comment by zzrough** [comment]
@ericdallo it's been a long time since this is unused anymore. Nowadays gnome shell version checking is disabled in all distros. This is the 
`disable-extension-version-validation` gnome shell key, that was introduced 6y ago and enabled 3y ago

**Comment by ericdallo** [comment]
Thanks for the explanation @zzrough
