### ISSUE TITLE
Support for Gnome 3.38.1

### ISSUE THREAD

**Issue by anubhav4sachan** [zzrough/gs-extensions-drop-down-terminal#246]
Firstly, this is a great extension. I loved using it.

But since the upgrade of Ubuntu to 20.10 (and implicit upgrade of Gnome to 3.38.1), the "error" is being displayed as attached in the screenshot.

Would love to have the support for 3.38.1

![Screenshot from 2020-10-22 22-03-58](https://user-images.githubusercontent.com/28740119/96902739-869b7000-14b2-11eb-96e3-13335322025c.png)

**Comment by gregorydk** [comment]
Fix: https://github.com/zzrough/gs-extensions-drop-down-terminal/pull/245/commits/b048aef3ca9f7bd76b1cab0c7068a1b0962f41b1

**Comment by armaccloud** [comment]
When will this fixed extension / version be available on extensions.gnome.org?

**Comment by anubhav4sachan** [comment]
> When will this fixed extension / version be available on extensions.gnome.org?

Can't say for sure, at present. 
Till then, use the fix from @gregorydk, and enjoy.
