### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by xtra25** [zzrough/gs-extensions-drop-down-terminal#52]
It would be great to be able to change the size of the font so those with low vision could see properly.

Thanks

**Comment by ChillerDragon** [comment]
Yea @zzrough the font size works in some cases. But it does not solve the use case of times you want to zoom in or out. Also I use two screens one is fullhd and one 4k and to get the scaling properly I keep it normal sized by default and zoom in on the 4k screen. So a ``ctrl`` + ``-`` and ``+`` bind would be really helpful.
