### ISSUE TITLE
terminal gets cut off

### ISSUE THREAD

**Issue by matter123** [zzrough/gs-extensions-drop-down-terminal#53]
Sometimes the terminal gets cut off, it always gets cut off on the right. Im running fedora 19 kernel 3.9.5.
![missing](https://f.cloud.github.com/assets/714007/1187868/388ca058-23a3-11e3-8083-ef589bf63376.png)

**Comment by matter123** [comment]
It appears fine now. Thank you for looking into this

**Comment by zzrough** [comment]
Thanks for the update!
