### ISSUE TITLE
vte 0.34.8 transparency fixed in 0.34.9

### ISSUE THREAD

**Issue by Kami-no** [zzrough/gs-extensions-drop-down-terminal#82]
http://rpmfind.net/linux/RPM/fedora/updates/20/i386/vte3-devel-0.34.9-3.fc20.i686.html

Any plans to return the transparency?

**Comment by deronnax** [comment]
transparency is gone on Fedora 21+Gnome 3.14.2 :'(

**Comment by zzrough** [comment]
It's been fixed for a loooooong time. I simply did not close the issue. It depends on your distribution though: at least Fedora and Arch have the necessary patch to make it work.
