### ISSUE TITLE
drop down terminal is displaced a bit downwards

### ISSUE THREAD

**Issue by lordadamson** [zzrough/gs-extensions-drop-down-terminal#92]
![screenshot from 2015-01-05 14 23 56](https://cloud.githubusercontent.com/assets/6195060/5613023/894c31c4-94e6-11e4-97da-9035d21ea049.png)

I'm using fedora 21 on macbook pro 11,1 (late 2013)
maybe it has to do with retina display?

kernel: 3.17.7-300.fc21.x86_64

note: I love drop down terminal :)

**Comment by zzrough** [comment]
Thanks.

Ha funny, I just fixed that a couple of days ago. I'll release the version in a couple of days I think. See the closed issue https://github.com/zzrough/gs-extensions-drop-down-terminal/issues/84

So I'm closing this one as it's a duplicate.
