### ISSUE TITLE
Gap between gnome menu bar and drop down terminal on HiDPI display

### ISSUE THREAD

**Issue by cwawak** [zzrough/gs-extensions-drop-down-terminal#96]
On a new Fedora 21 install, with the (I think, latest) version of Drop Down Terminal, I noticed that there is a gap between the menu bar and the drop down terminal. It's there regardless of where the application is, if the application is maxmized, or even full-screened. This has always worked fine on my systems, and the only thing that's different here is that this is a HiDPI display. I'm at 2x scaling, and resolution is 2560x1440.

I expected the drop down to either line up with the menu bar, or with the top of the screen, not leave a gap.

I've attached a screen shot below. Thanks!

![screenshot from 2015-02-04 22 23 35](https://cloud.githubusercontent.com/assets/1583877/6054524/9f20440c-acbc-11e4-9ec7-f11da9cb3ca6.png)

**Comment by cwawak** [comment]
... and I don't know how to search. Sorry!

**Comment by zzrough** [comment]
I suppose you found out it's a duplicate of #84, which has been fixed already.
